{
  "uid" : "22b9c85a829eec36",
  "name" : "test_xfail",
  "fullName" : "test.allure_status_test#test_xfail",
  "historyId" : "f37ad0a404a467cce5f63f51cfe5219f",
  "time" : {
    "start" : 1620246647429,
    "stop" : 1620246647429,
    "duration" : 0
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL Some xfail reason\n\nAssertionError: Assertion failed\nassert False",
  "statusTrace" : "@pytest.mark.xfail(reason=\"Some xfail reason\")\n    def test_xfail():\n>       assert False, \"Assertion failed\"\nE       AssertionError: Assertion failed\nE       assert False\n\ntest/allure_status_test.py:24: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.xfail(reason='Some xfail reason')"
  }, {
    "name" : "parentSuite",
    "value" : "test"
  }, {
    "name" : "suite",
    "value" : "allure_status_test"
  }, {
    "name" : "host",
    "value" : "fv-az231-191"
  }, {
    "name" : "thread",
    "value" : "2873-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test.allure_status_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "tags" : [ "@pytest.mark.xfail(reason='Some xfail reason')" ]
  },
  "source" : "22b9c85a829eec36.json",
  "parameterValues" : [ ]
}